### ISSUE TITLE
'Incompatible plugin version with new templates' error

### ISSUE THREAD

**Issue by haani-niyaz** [nwops/puppet-retrospec#48] opened 2016-02-03 02:55 UTC
When running `puppet-retrospec` I get the following error:

    Error running hook: /home/vagrant/.retrospec/repos/retrospec-puppet-templates/clone-hook
    Newer version of retrospec-puppet detected, please update: gem update puppet-retrospec
    Incompatible plugin version with new templates, will not continue without update

Despite updating `puppet-retrospec` it still gives me the same error.

    vagrant$ bundle show puppet-retrospec
    /home/vagrant/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/puppet-retrospec-0.12.0

**Comment by logicminds** [comment] 2016-02-03 03:01
I think bundler might be the cause.  Can you install puppet-retrospec outside of bundler.

**Comment by haani-niyaz** [comment] 2016-02-03 03:04
@logicminds , This has previously worked with `bundler` but will give it a shot anyway.

**Comment by logicminds** [comment] 2016-02-03 03:08
https://github.com/nwops/retrospec-templates/blob/master/clone-hook#L92

This was some new code I added to the templates.  This would be the culprit. For some reason its finding  an older version or something on your system.   I am not sure if this works correctly using bundler: https://github.com/nwops/retrospec-templates/blob/master/clone-hook#L80.

**Comment by logicminds** [comment] 2016-02-03 03:23
As for the reason why it would not create the spec files.  I assume you have some manifests? 

 I will make a small change to the clone hook which should allow you to update the templates.  I have never seen this though. You will need to issue a `git pull` inside /home/vagrant/.retrospec/repos/retrospec-puppet-templates to get the latest templates once I make the change.

**Comment by haani-niyaz** [comment] 2016-02-03 04:05
Thanks. Your probably right about this being a `bundler` issue but any help is appreciated!

**Comment by logicminds** [comment] 2016-02-03 05:22
Could be a rbenv issue.  The hooks use `/usr/bin/env ruby` so whatever that executes might lead to the problem.

**Comment by logicminds** [comment] 2016-02-18 21:21
any update on this?

**Comment by logicminds** [comment] 2016-02-20 18:05
The original issue was fixed in a change to the clone hook.  For the other issue please refer to #51

**Closed by logicminds** 2016-02-20 18:05 UTC
Labels: bug
